### ISSUE TITLE
Show income / expense values in the statistics

### ISSUE THREAD

**Issue by TalviT** [pmiddend/piggybudget#12]
Besides the distribution of incomes/expenses it would be nice to see exactly how much you have spent, like this:

![Mockup](https://user-images.githubusercontent.com/18188251/54126128-22c05280-4407-11e9-8981-e46d3e1febff.png)

**Comment by pmiddend** [comment]
Yep, that was actually pretty easy to implement and looks fine, I think. Will be included in 2.5 in a few days:

![Screenshot_1552664447](https://user-images.githubusercontent.com/178496/54443559-1c044900-4741-11e9-9ba2-50e0f9d34634.png)

**Comment by TalviT** [comment]
Great, thanks! I'm looking forward to the release!
I had another idea. In order to keep the view as clean as possible and not to overload it with information, you could only display this view by tapping on the diagramm. Whereby that is a matter of taste.
