### ISSUE TITLE
App crashes when trying to share csv file

### ISSUE THREAD

**Issue by jubreal** [pmiddend/piggybudget#15]
#### Expected behavior
Users should be able to be able to share csv files when the "share csv" button is clicked.

#### Actual behavior
The application closes and crashed when user click on "share csv".

#### How to reproduce
Download and install the latest release of the app.

Launch the app.

Grant all permissions.

Click on the floating action button (the 3 horizontal dots) in the top right corner

Click on the "Share CSV" option.

It will be observed that the app crashes and closes. Hence, the bug.

Browser: Piggy budget version 2.5
Operating system: android version 6.0

#### Recording Of The Bug
https://youtu.be/PZtSl0Da_rU

####LOG
``` 04-10 13:23:40.673 I/ReactNativeJS(14344): Running application "piggybudget" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
04-10 13:23:40.824 I/BufferQueueProducer(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity](this:0x7f7d3a3000,id:597,api:1,p:14344,c:271) new GraphicBuffer needed
04-10 13:23:40.838 I/BufferQueueProducer(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity](this:0x7f7d3a3000,id:597,api:1,p:14344,c:271) queueBuffer: fps=0.40 dur=2530.76 max=2530.76 min=2530.76
04-10 13:23:40.842 I/BufferQueueProducer(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity](this:0x7f7d3a3000,id:597,api:1,p:14344,c:271) new GraphicBuffer needed
04-10 13:23:41.280 I/BufferQueueProducer(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity](this:0x7f7d3a3000,id:597,api:1,p:14344,c:271) new GraphicBuffer needed
04-10 13:23:42.448 I/BufferQueueProducer(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity](this:0x7f7d3a3000,id:597,api:1,p:14344,c:271) queueBuffer: fps=3.73 dur=1610.20 max=818.23 min=7.13
04-10 13:23:43.617 I/BufferQueueProducer(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity](this:0x7f7d3a3000,id:597,api:1,p:14344,c:271) queueBuffer: fps=4.28 dur=1168.76 max=594.79 min=8.61
04-10 13:23:45.950 I/am_crash(944): [14344,0,de.php_tech.piggybudget,948452932,android.util.AndroidRuntimeException,Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?,ContextImpl.java,677]
04-10 13:23:45.956 I/am_finish_activity(944): [0,32879754,112609,de.php_tech.piggybudget/.MainActivity,force-crash]
04-10 13:23:45.947 E/AndroidRuntime(14344): Process: de.php_tech.piggybudget, PID: 14344
04-10 13:23:45.947 E/AndroidRuntime(14344): 	at de.php_tech.piggybudget.ExportIntentModule.exportCsv(ExportIntentModule.java:54)
04-10 13:23:45.994 I/am_pause_activity(944): [0,32879754,de.php_tech.piggybudget/.MainActivity]
04-10 13:23:45.956 W/ActivityManager(944):   Force finishing activity de.php_tech.piggybudget/.MainActivity
04-10 13:23:45.957 V/WindowManager(944): findFocusedWindow: Found new focus @ 12 = Window{e58d660 u0 de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity}
04-10 13:23:45.959 V/WindowManager(944): Set focused app to: AppWindowToken{52b76d7 token=Token{13e656 ActivityRecord{e87871 u0 com.infinix.xlauncher/com.android.launcher3.Launcher t112575}}} old focus=AppWindowToken{3922718 token=Token{f5c1afb ActivityRecord{1f5b48a u0 de.php_tech.piggybudget/.MainActivity t112609}}} moveFocusNow=true
04-10 13:23:45.965 D/AES     (944):     process : de.php_tech.piggybudget
04-10 13:23:45.965 D/AES     (944):      module : de.php_tech.piggybudget v25 (2.5)
04-10 13:23:45.965 D/AEE/LIBAEE(944): shell: raise_exp(4, 14344, -1361051648, de.php_tech.piggybudget, 0x0x7f767e1720, 0x0x0)
04-10 13:23:45.968 V/WindowManager(944): Changing focus from Window{e58d660 u0 de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4506 com.android.server.am.ActivityManagerService.setFocusedActivityLocked:2873 com.android.server.am.ActivityStackSupervisor.moveHomeStackTaskToTop:575 com.android.server.am.ActivityStack.adjustFocusedActivityLocked:3141 
04-10 13:23:45.969 I/AEE/AED (14395): [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 14344, tid: -1361051648, name: UNKNOWN  >>> de.php_tech.piggybudget <<<
04-10 13:23:45.969 V/AEE/AED (14395): dashboard_record_update() : rec->module = de.php_tech.piggybudget 
04-10 13:23:45.969 I/WindowManager(944): Focus moving from Window{e58d660 u0 de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity} to null
04-10 13:23:45.970 I/WindowManager(944): Losing focus: Window{e58d660 u0 de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity}

**Comment by pmiddend** [comment]
Thanks for reporting this to me. I didn't actually test with Android version 6.0. Will do that soon and report back. Probably, all four of your issues are related to that.

**Comment by jubreal** [comment]
Thanks for the reply . I'll be expecting your update after running the test on OS 6.0

**Comment by pmiddend** [comment]
Sadly, I was not able to reproduce this with a virtual machine containing Android 6.

**Comment by jubreal** [comment]
Did you try it with an emulator or a real device?
And also can you check the logcat contained in each report.

**Comment by pmiddend** [comment]
Sorry for the late reply. I only have an Android emulator available at the moment.
I also looked at the logcat output and found nothing of interest. I'd have expected some sort of error message, but there doesn't seem to be any.

**Comment by Danfernbanck** [comment]
My phone's report with this issue (please help) :
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:687)
	at android.app.ContextImpl.startActivity(ContextImpl.java:674)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
	at de.php_tech.piggybudget.ExportIntentModule.exportCsv(ExportIntentModule.java:54)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:207)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:818)

**Comment by pmiddend** [comment]
@Danfernbanck Oh, that actually helps! I'll try adding a specific line of code and we'll see if this works.
