### ISSUE TITLE
Modifying/deleting existing expense

### ISSUE THREAD

**Issue by vonneudeck** [pmiddend/piggybudget#2]
I made a test expense and I could not figure out how to delete or modify it after I saved it.
Did I just not find the button or is that feature missing?

**Comment by pmiddend** [comment]
I'm sorry for the confusion. Indeed, this feature has not been implemented yet.

**Comment by mwip** [comment]
This is also true for any income item

**Comment by pmiddend** [comment]
Starting at 2.0, this is now implemented (see the History tab, then press the according button to open a menu).
