### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by davidmind** [pmiddend/piggybudget#21]
Hi, @pmiddend I am graphics designer, I just create a logo that help reflect the professional look of your project. Here is a quick view. If you like it I will proceed to make other sizes, while I also share editable files
![piggy-budget.png](https://cdn.steemitimages.com/DQmWxvSeC7ChmqCdwXapa88NkbxR6KygebHXon2DQPccT2C/piggy-budget.png)

![piggy-2.png](https://cdn.steemitimages.com/DQmbHoKYZtxtfauTMdz3ZAAiYPD9YkJAh7cbGdsMBVizMHd/piggy-2.png)

**Comment by davidmind** [comment]
@pmiddend @Akito13 are you there?

**Comment by Akito13** [comment]
> 
> 
> @pmiddend @Akito13 are you there?

Yes. @pmiddend can decide to accept or decline your proposition.

**Comment by davidmind** [comment]
Ok, i will wait till when respond @pmiddend

**Comment by pmiddend** [comment]
First of all, thanks @davidmind for your work. The logo looks good and professional. However, I do have a sentimental attachment to the current logo. My girlfriend designed it, and she is really fond of the app. I'd rather not change it. I hope you understand.
