### ISSUE TITLE
CSV Feature Crashes The App

### ISSUE THREAD

**Issue by autofreak** [pmiddend/piggybudget#9]
This is the second issue that I have submitted, I really like this app and developers effort is well appreciated.

Whenever I try to open CSV (new feature), the app always crash. Check this video https://youtu.be/uc1OHBdHk68, I tried to record my screen.

**Comment by pmiddend** [comment]
Oh, sorry for that. Could you tell me which Android version you are running currently?

**Comment by paulle** [comment]
Sharing CSV-file is working here. Android 9, Sony xz2

**Comment by autofreak** [comment]
I am using Android 7 on Infinix

**Comment by pmiddend** [comment]
Okay, I'll try an emulator for 7 and see if the problem occurs. Stay tuned!

**Comment by pmiddend** [comment]
@autofreak Thanks for reporting this issue, it's fixed in the latest version.
